//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloqueAcademicoXPlanDeEstudio
    {
        public BloqueAcademicoXPlanDeEstudio()
        {
            this.BloqueXPlanXCursoes = new HashSet<BloqueXPlanXCurso>();
        }
    
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int BloqueID { get; set; }
    
        public virtual BloqueAcademico BloqueAcademico { get; set; }
        public virtual PlanesDeEstudio PlanesDeEstudio { get; set; }
        public virtual ICollection<BloqueXPlanXCurso> BloqueXPlanXCursoes { get; set; }
    }
}
