
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SACAAE.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CursosXGrupo
{

    public CursosXGrupo()
    {

        this.Detalle_Curso = new HashSet<Detalle_Curso>();

    }


    public int ID { get; set; }

    public int Curso { get; set; }

    public int Grupo { get; set; }



    public virtual Grupo Grupo1 { get; set; }

    public virtual ICollection<Detalle_Curso> Detalle_Curso { get; set; }

    public virtual Curso Curso1 { get; set; }

}

}
