//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public Plaza()
        {
            this.PlazaXProfesors = new HashSet<PlazaXProfesor>();
        }
    
        public int ID { get; set; }
        public string Codigo_Plaza { get; set; }
        public string Tipo_de_plaza { get; set; }
        public string Tipo_segun_tiempo { get; set; }
        public Nullable<int> Horas_Totales { get; set; }
        public Nullable<int> Tiempo_de_vigencia { get; set; }
    
        public virtual ICollection<PlazaXProfesor> PlazaXProfesors { get; set; }
    }
}
