//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACAAE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores
    {
        public Profesores()
        {
            this.ComisionesXProfesor = new HashSet<ComisionesXProfesor>();
            this.PlazaXProfesor = new HashSet<PlazaXProfesor>();
            this.ProfesoresXCurso = new HashSet<ProfesoresXCurso>();
            this.ProyectosXProfesor = new HashSet<ProyectosXProfesor>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Link { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<ComisionesXProfesor> ComisionesXProfesor { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<PlazaXProfesor> PlazaXProfesor { get; set; }
        public virtual ICollection<ProfesoresXCurso> ProfesoresXCurso { get; set; }
        public virtual ICollection<ProyectosXProfesor> ProyectosXProfesor { get; set; }
    }
}
