
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SACAAE.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProfesoresXCurso
{

    public ProfesoresXCurso()
    {

        this.Detalle_Curso = new HashSet<Detalle_Curso>();

    }


    public int Id { get; set; }

    public int Profesor { get; set; }

    public Nullable<int> Horas { get; set; }



    public virtual ICollection<Detalle_Curso> Detalle_Curso { get; set; }

    public virtual Profesore Profesore { get; set; }

}

}
